namespace GreenLifeManagementSystem.Forms
{
    partial class AdminDashboard
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.panelSidebar = new System.Windows.Forms.Panel();
            this.btnReports = new System.Windows.Forms.Button();
            this.btnManageUsers = new System.Windows.Forms.Button();
            this.btnManageOrders = new System.Windows.Forms.Button();
            this.btnManageProducts = new System.Windows.Forms.Button();
            this.lblNav = new System.Windows.Forms.Label();
            this.lblLogo = new System.Windows.Forms.Label();
            this.panelHeader = new System.Windows.Forms.Panel();
            this.btnLogout = new System.Windows.Forms.Button();
            this.lblDashboardSub = new System.Windows.Forms.Label();
            this.lblDashboardTitle = new System.Windows.Forms.Label();
            this.grpTotalProducts = new System.Windows.Forms.GroupBox();
            this.lblTotalProducts = new System.Windows.Forms.Label();
            this.grpPendingOrders = new System.Windows.Forms.GroupBox();
            this.lblPendingOrders = new System.Windows.Forms.Label();
            this.grpLowStock = new System.Windows.Forms.GroupBox();
            this.lblLowStock = new System.Windows.Forms.Label();
            this.lblRecentOrdersHeader = new System.Windows.Forms.Label();
            this.dgvRecentOrders = new System.Windows.Forms.DataGridView();
            this.lblLowStockHeader = new System.Windows.Forms.Label();
            this.dgvLowStockProducts = new System.Windows.Forms.DataGridView();
            this.panelSidebar.SuspendLayout();
            this.panelHeader.SuspendLayout();
            this.grpTotalProducts.SuspendLayout();
            this.grpPendingOrders.SuspendLayout();
            this.grpLowStock.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvRecentOrders)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvLowStockProducts)).BeginInit();
            this.SuspendLayout();
            this.panelSidebar.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panelSidebar.Controls.Add(this.btnReports);
            this.panelSidebar.Controls.Add(this.btnManageUsers);
            this.panelSidebar.Controls.Add(this.btnManageOrders);
            this.panelSidebar.Controls.Add(this.btnManageProducts);
            this.panelSidebar.Controls.Add(this.lblNav);
            this.panelSidebar.Controls.Add(this.lblLogo);
            this.panelSidebar.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelSidebar.Location = new System.Drawing.Point(0, 0);
            this.panelSidebar.Name = "panelSidebar";
            this.panelSidebar.Size = new System.Drawing.Size(200, 600);
            this.panelSidebar.TabIndex = 0;
            this.btnReports.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReports.Location = new System.Drawing.Point(10, 270);
            this.btnReports.Name = "btnReports";
            this.btnReports.Size = new System.Drawing.Size(180, 40);
            this.btnReports.TabIndex = 5;
            this.btnReports.Text = "Reports";
            this.btnReports.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnReports.UseVisualStyleBackColor = true;
            this.btnReports.Click += new System.EventHandler(this.btnReports_Click);
            this.btnManageUsers.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnManageUsers.Location = new System.Drawing.Point(10, 220);
            this.btnManageUsers.Name = "btnManageUsers";
            this.btnManageUsers.Size = new System.Drawing.Size(180, 40);
            this.btnManageUsers.TabIndex = 4;
            this.btnManageUsers.Text = "Users";
            this.btnManageUsers.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManageUsers.UseVisualStyleBackColor = true;
            this.btnManageUsers.Click += new System.EventHandler(this.btnManageUsers_Click);
            this.btnManageOrders.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnManageOrders.Location = new System.Drawing.Point(10, 170);
            this.btnManageOrders.Name = "btnManageOrders";
            this.btnManageOrders.Size = new System.Drawing.Size(180, 40);
            this.btnManageOrders.TabIndex = 3;
            this.btnManageOrders.Text = "Orders";
            this.btnManageOrders.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManageOrders.UseVisualStyleBackColor = true;
            this.btnManageOrders.Click += new System.EventHandler(this.btnManageOrders_Click);
            this.btnManageProducts.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnManageProducts.Location = new System.Drawing.Point(10, 120);
            this.btnManageProducts.Name = "btnManageProducts";
            this.btnManageProducts.Size = new System.Drawing.Size(180, 40);
            this.btnManageProducts.TabIndex = 2;
            this.btnManageProducts.Text = "Products";
            this.btnManageProducts.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManageProducts.UseVisualStyleBackColor = true;
            this.btnManageProducts.Click += new System.EventHandler(this.btnManageProducts_Click);
            this.lblNav.AutoSize = true;
            this.lblNav.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblNav.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.lblNav.Location = new System.Drawing.Point(10, 90);
            this.lblNav.Name = "lblNav";
            this.lblNav.Size = new System.Drawing.Size(89, 20);
            this.lblNav.TabIndex = 1;
            this.lblNav.Text = "NAVIGATION";
            this.lblLogo.AutoSize = true;
            this.lblLogo.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblLogo.Location = new System.Drawing.Point(10, 20);
            this.lblLogo.Name = "lblLogo";
            this.lblLogo.Size = new System.Drawing.Size(178, 56);
            this.lblLogo.TabIndex = 0;
            this.lblLogo.Text = "LOGO Admin\r\nDashboard";
            this.panelHeader.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panelHeader.Controls.Add(this.btnLogout);
            this.panelHeader.Controls.Add(this.lblDashboardSub);
            this.panelHeader.Controls.Add(this.lblDashboardTitle);
            this.panelHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelHeader.Location = new System.Drawing.Point(200, 0);
            this.panelHeader.Name = "panelHeader";
            this.panelHeader.Size = new System.Drawing.Size(800, 80);
            this.panelHeader.TabIndex = 1;
            this.btnLogout.Location = new System.Drawing.Point(680, 20);
            this.btnLogout.Name = "btnLogout";
            this.btnLogout.Size = new System.Drawing.Size(94, 40);
            this.btnLogout.TabIndex = 2;
            this.btnLogout.Text = "Logout";
            this.btnLogout.UseVisualStyleBackColor = true;
            this.btnLogout.Click += new System.EventHandler(this.btnLogout_Click);
            this.lblDashboardSub.AutoSize = true;
            this.lblDashboardSub.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.lblDashboardSub.Location = new System.Drawing.Point(20, 45);
            this.lblDashboardSub.Name = "lblDashboardSub";
            this.lblDashboardSub.Size = new System.Drawing.Size(209, 20);
            this.lblDashboardSub.TabIndex = 1;
            this.lblDashboardSub.Text = "Summary cards and key alerts";
            this.lblDashboardTitle.AutoSize = true;
            this.lblDashboardTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblDashboardTitle.Location = new System.Drawing.Point(20, 15);
            this.lblDashboardTitle.Name = "lblDashboardTitle";
            this.lblDashboardTitle.Size = new System.Drawing.Size(210, 28);
            this.lblDashboardTitle.TabIndex = 0;
            this.lblDashboardTitle.Text = "Dashboard Overview";
            this.grpTotalProducts.Controls.Add(this.lblTotalProducts);
            this.grpTotalProducts.Font = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.grpTotalProducts.Location = new System.Drawing.Point(220, 100);
            this.grpTotalProducts.Name = "grpTotalProducts";
            this.grpTotalProducts.Size = new System.Drawing.Size(240, 120);
            this.grpTotalProducts.TabIndex = 2;
            this.grpTotalProducts.TabStop = false;
            this.grpTotalProducts.Text = "Total Products";
            this.lblTotalProducts.AutoSize = true;
            this.lblTotalProducts.Font = new System.Drawing.Font("Segoe UI", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblTotalProducts.Location = new System.Drawing.Point(20, 50);
            this.lblTotalProducts.Name = "lblTotalProducts";
            this.lblTotalProducts.Size = new System.Drawing.Size(65, 38);
            this.lblTotalProducts.TabIndex = 0;
            this.lblTotalProducts.Text = "###";
            this.grpPendingOrders.Controls.Add(this.lblPendingOrders);
            this.grpPendingOrders.Font = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.grpPendingOrders.Location = new System.Drawing.Point(480, 100);
            this.grpPendingOrders.Name = "grpPendingOrders";
            this.grpPendingOrders.Size = new System.Drawing.Size(240, 120);
            this.grpPendingOrders.TabIndex = 3;
            this.grpPendingOrders.TabStop = false;
            this.grpPendingOrders.Text = "Pending Orders";
            this.lblPendingOrders.AutoSize = true;
            this.lblPendingOrders.Font = new System.Drawing.Font("Segoe UI", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblPendingOrders.Location = new System.Drawing.Point(20, 50);
            this.lblPendingOrders.Name = "lblPendingOrders";
            this.lblPendingOrders.Size = new System.Drawing.Size(65, 38);
            this.lblPendingOrders.TabIndex = 0;
            this.lblPendingOrders.Text = "###";
            this.grpLowStock.Controls.Add(this.lblLowStock);
            this.grpLowStock.Font = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.grpLowStock.Location = new System.Drawing.Point(740, 100);
            this.grpLowStock.Name = "grpLowStock";
            this.grpLowStock.Size = new System.Drawing.Size(240, 120);
            this.grpLowStock.TabIndex = 4;
            this.grpLowStock.TabStop = false;
            this.grpLowStock.Text = "Low Stock Alerts";
            this.lblLowStock.AutoSize = true;
            this.lblLowStock.Font = new System.Drawing.Font("Segoe UI", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblLowStock.Location = new System.Drawing.Point(20, 50);
            this.lblLowStock.Name = "lblLowStock";
            this.lblLowStock.Size = new System.Drawing.Size(65, 38);
            this.lblLowStock.TabIndex = 0;
            this.lblLowStock.Text = "###";
            this.lblRecentOrdersHeader.AutoSize = true;
            this.lblRecentOrdersHeader.Font = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblRecentOrdersHeader.Location = new System.Drawing.Point(220, 240);
            this.lblRecentOrdersHeader.Name = "lblRecentOrdersHeader";
            this.lblRecentOrdersHeader.Size = new System.Drawing.Size(130, 23);
            this.lblRecentOrdersHeader.TabIndex = 5;
            this.lblRecentOrdersHeader.Text = "Recent Orders";
            this.dgvRecentOrders.AllowUserToAddRows = false;
            this.dgvRecentOrders.AllowUserToDeleteRows = false;
            this.dgvRecentOrders.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvRecentOrders.BackgroundColor = System.Drawing.Color.White;
            this.dgvRecentOrders.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvRecentOrders.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvRecentOrders.Location = new System.Drawing.Point(220, 268);
            this.dgvRecentOrders.Name = "dgvRecentOrders";
            this.dgvRecentOrders.ReadOnly = true;
            this.dgvRecentOrders.RowHeadersVisible = false;
            this.dgvRecentOrders.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvRecentOrders.Size = new System.Drawing.Size(370, 300);
            this.dgvRecentOrders.TabIndex = 6;
            this.lblLowStockHeader.AutoSize = true;
            this.lblLowStockHeader.Font = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblLowStockHeader.Location = new System.Drawing.Point(610, 240);
            this.lblLowStockHeader.Name = "lblLowStockHeader";
            this.lblLowStockHeader.Size = new System.Drawing.Size(160, 23);
            this.lblLowStockHeader.TabIndex = 7;
            this.lblLowStockHeader.Text = "Low Stock Products";
            this.dgvLowStockProducts.AllowUserToAddRows = false;
            this.dgvLowStockProducts.AllowUserToDeleteRows = false;
            this.dgvLowStockProducts.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvLowStockProducts.BackgroundColor = System.Drawing.Color.White;
            this.dgvLowStockProducts.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvLowStockProducts.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvLowStockProducts.Location = new System.Drawing.Point(610, 268);
            this.dgvLowStockProducts.Name = "dgvLowStockProducts";
            this.dgvLowStockProducts.ReadOnly = true;
            this.dgvLowStockProducts.RowHeadersVisible = false;
            this.dgvLowStockProducts.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvLowStockProducts.Size = new System.Drawing.Size(370, 300);
            this.dgvLowStockProducts.TabIndex = 8;
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1000, 600);
            this.Controls.Add(this.dgvLowStockProducts);
            this.Controls.Add(this.lblLowStockHeader);
            this.Controls.Add(this.dgvRecentOrders);
            this.Controls.Add(this.lblRecentOrdersHeader);
            this.Controls.Add(this.grpLowStock);
            this.Controls.Add(this.grpPendingOrders);
            this.Controls.Add(this.grpTotalProducts);
            this.Controls.Add(this.panelHeader);
            this.Controls.Add(this.panelSidebar);
            this.Name = "AdminDashboard";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Admin Dashboard";
            this.Load += new System.EventHandler(this.AdminDashboard_Load);
            this.panelSidebar.ResumeLayout(false);
            this.panelSidebar.PerformLayout();
            this.panelHeader.ResumeLayout(false);
            this.panelHeader.PerformLayout();
            this.grpTotalProducts.ResumeLayout(false);
            this.grpTotalProducts.PerformLayout();
            this.grpPendingOrders.ResumeLayout(false);
            this.grpPendingOrders.PerformLayout();
            this.grpLowStock.ResumeLayout(false);
            this.grpLowStock.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvRecentOrders)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvLowStockProducts)).EndInit();
            this.ResumeLayout(false);

        }

        private System.Windows.Forms.Panel panelSidebar;
        private System.Windows.Forms.Label lblNav;
        private System.Windows.Forms.Label lblLogo;
        private System.Windows.Forms.Button btnManageUsers;
        private System.Windows.Forms.Button btnManageOrders;
        private System.Windows.Forms.Button btnManageProducts;
        private System.Windows.Forms.Button btnReports;
        private System.Windows.Forms.Panel panelHeader;
        private System.Windows.Forms.Button btnLogout;
        private System.Windows.Forms.Label lblDashboardSub;
        private System.Windows.Forms.Label lblDashboardTitle;
        private System.Windows.Forms.GroupBox grpTotalProducts;
        private System.Windows.Forms.Label lblTotalProducts;
        private System.Windows.Forms.GroupBox grpPendingOrders;
        private System.Windows.Forms.Label lblPendingOrders;
        private System.Windows.Forms.GroupBox grpLowStock;
        private System.Windows.Forms.Label lblLowStock;
        private System.Windows.Forms.Label lblRecentOrdersHeader;
        private System.Windows.Forms.DataGridView dgvRecentOrders;
        private System.Windows.Forms.Label lblLowStockHeader;
        private System.Windows.Forms.DataGridView dgvLowStockProducts;
    }
}